export { default as ImageBackground } from './ImageBackground'
export { default as Blogs } from './Blogs'
export { default as BlogTemplate } from './BlogTemplate'
export { default as Footer } from './Footer'
export { default as Landing} from './Landing'
export { default as Intro } from './Intro'
export { default as About } from './About'
export { default as Showcase } from './Showcase'
export { default as Loading } from './Loading'
export { default as SEO } from './SEO'